
# beliefenvironment
#      Description: short summary of the environment 
#      Objective: Objective of the agent in the environment
#      Actionset: Set of valid actions for the environment.
#      beliefaxioms : belief axioms with level of belief. Level of belief can be weak, moderate, strong and very strong

# DEFAULTACTPLANJECTIVE = """ You are an action planner for an AI agent. 
# Use the belief axioms, the objective of the environment model, the previous action perception trace and output of the critique to provide an action plan.
# The action should be inline with the objective and should get positive feedback from the critique in long term.
# You may use chain of thoughts to generate action plan.
# The output action plan should be concise and in algorithm format and contain enough detail to convert into a complete code.
# Keep a balance of exploration and exploitation in the actionplan to know more about the environment and meet the objective in the already known environment respectively.
# In the initial phase when the environment is not known well explore more to know the environment. 
# The output should be in following json format. In no case the output should deviate from the following json format.
# {"actionplan": <algorithm of actionplan in detail text format>,
# "subproblems" : [<distinct list of subproblems to be solved to carry out the action plan.>]
# }
#"""
# actionplantemplate = """System: {objective}
    # Environment:
        # {beliefenvironment}  
      
    # Action Perception trace:
        # {ACPtrace}
    
    # Critque:
       # {critique}
    
    # Perception: {lastperception}
    # Action: """
    
    
##Following is the critique provided by another expert agent on the previous action plan based on the internal criterias of the AI agent for generating an action plan
#Internal critique:
#    {internalcritique}    


actionplantemplate = """System: You are an AI action planner for an autonomous agent. You are situated in the following environment.
 Environment:
        {beliefenvironment}  

Use the belief axioms to plan out and deduce valid set to actions that can be taken in the environment.
The action plan should be directed to meet the objective of the environment and maximize the future cumulative reward.
Keep a balance of exploration and exploitation in the actionplan to know more about the environment and meet the objective in the already known environment respectively.
The action plan should involve executing only stored function modules. 
The action plan may include basic logical constructs like looping, conditional statements, arithmetic and logical operations.
The action plan should not have infinite loops. Preferably it should be concise. 
The action plan should not have contradicting logic.

Following are the historical action plans provided by you and the corresponding responses generated by the environment on executing the action plan.
Action plan history:
   {ACPtrace}

Following is the critique provided by an expert agent on the previous action plan based on the environment feedback.
Critque:
    {critique}

Following is the list of callable function modules.    
stored function modules:
    {relatedactions}

Use the previous critique to refine or reuse the action plan. The action plan should get positive feedback from the critique in long term.

The output should be in following json format. In no case the output should deviate from the following json format.
{{"planid" : <8 digit alphanumeric id>,
"actionplan": <algorithm of actionplan in plaintext. It should contain enough details to convert it into code. If a function module is called that takes input parameters, then properly supply the value of the input parameters in the actionplan. Do not call no-existent functions in allowed actions. Do not create infinite loops. Do not make up new actions or functions. Do not generate plans in separate lines.>,
"requiredactions" : [<distinct subset of moduleid from stored function modules needed to carry out the action plan. All modules should be strictly from stored function modules and do not make up any moduleids.>],
"cumulative reward" : 0
}}

Here are some example output.

Example output 1
{{"planid" : "jkuhy85r",
"actionplan": "Get an input from user using the textread function with the argument 'Ask me a question'. Store the response in a variable var1. Send the same response to konwledgebase using the function fun_knowledge with the argument as the variable var1. store the response in another variable var2. if value of the variable var2 is not null then show the response to user by using the function showdata with argument as variable var2.", "requiredactions" :["XYFG2780","FAX785UY","YTRU87TR"],
"cumulative reward" : 0}} 

Example 2
{{"planid" : "shyh36hd",
"actionplan": "Get an image file from user using the fileinput function with the argument 'Upload and image file'. Get an input question from user using the textread function with the argument 'Ask a question on the image'. Send the image and question to viperGPT using the function vipergpt with argument as a tuple of the uploaded image file and the question asked by the user. Return the response answer." , "requiredactions" :["XYFHG80","FTY785UY","YOPY87TR"],
"cumulative reward" : 0}} 

{errorfeedback}


AI: 

"""
    
ACTPLANPROMPTINPUTVARIABLES = ["beliefenvironment", "ACPtrace", "critique","relatedactions","errorfeedback"]


actionplancritiquetemplate = """System: You are a critique of generated action plan by an AI agent situated in an environment. 
Check if the action plan violates any constraints in the following belief axioms
Environment belief axioms:
    {beliefaxioms}  
 
Here is the action plan:
Action plan:
     {actplan}
 
Check if the action plan violates any of the following constraints
Constraints:
    The action plan should not have potential infinite loops.
    The action plan should not have contradicting logic
    
The output should always be in the following json format. In no case it should deviate from the following format.
{{
 "feedback": <valid if the action plan satisfies all the constraints and invalid if it doesnt>,
 "reason" : <concise reason of the feedback based on which the action plan can be corrected>
}}

AI: 
"""

ACTPLANCRITIQUEINPUTVARIABLES = ["beliefaxioms", "actplan"]

# DEFAULTACTOROBJECTIVE = """ You are part of an AI agent that converts action plan to concrete executable action in form of python code. 
# The action is executed in an external environment.
# Use the related action modules as reusable functions or combine and/or modify them to create a new action code as per the action plan.
# If Current code and code error is available then you need to modify the current code to remove the code errors. 
# The output should only be in the following json format. No other text should be there. Add escape charachters wherever required to make the following a valid json definately.
# {"description" : <a short description of the action not exceeding 100 tokens>,
# "code": "<executable python 3 code of the action. The output code should be complete and executable in itself. add escape charachter before double quotes  within the function definition>",
# "requirements": "<full function definition code from related action modules, if any to be used in the above code. add escape charachter before double quotes  within the function definition>",
# "functioncall": "<above function name>(<required argument values>)"
# }

# The structure of the code will be as follows:
# import <any required inbuilt python library>
# <New function defintion with arguments and proper indentation. function body may contain python loops, conditional statements, arithmetic operations, python inbuilt functions,
# logical operations, variable assignments, complex math operations, 
# function calls with appropriate parameters that to related action modules that are defined above.
# Always return the data that you want to send to the main AI agent. 
# The return data can be any data collected from the environment, user , other AI agent or ant specific return data mention in the action plan.
# The above function call should not be present here.>

# """
# actortemplate = """System: {objective}
    # Related action modules:
        # {actions}
    
    # Action plan: {actionplan}
    
    # Current code:
       # {currentcode}
    
    # Code error:
       # {error}
        
    # Action: """

#  , 
actortemplate = """System:  You are part of an AI agent that converts action plan to concrete executable action in form of python 3 code.
Try to write a general code so that it can be reused in other actionplans. 
The action is executed in an external environment. Following is the objective of AI agent in the environment.
Environment objective:
   {envobjective}

The actionplan is to meet the above objective. Following is the action plan.
Action plan: 
   {actionplan}

You can use the related function modules as reusable functions or combine and/or modify them to create a new action code as per the action plan. Following are the related function code that can be useful in constructing the action code.
Related function modules:
   {actions}

Previous action plan:
   {prevactionplan}
If previous action code is available then you may update the previous code to execute the current action plan mentioned above.

The output should only be in the following json format parsable in python3. No other text should be there. Add escape charachters wherever required to make the following a valid json definately.
{{
  "name": <a meaningful name of the action not exceeding 7 tokens>,
  "input parameter" : <required input parameters of the function in the following code. If no parameters are required then keep it blank enclosed with double quotes>, 
  "output" : <output returned by the function. If no output is returned then keep it blank enclosed with double quotes.>
  "description" : "<a short description of the action not exceeding 100 tokens>",
  "code": "<executable python 3 code of the action. The output code should be complete and executable in itself. add escape charachter before double quotes  within the function definition. Should not contain infinite loops. STRICTLY Don't make up any new function call apart from whatever available in Related function modules. Do not add same functions here which are there in requirements below.>",
  "requirements": "<full function definition code from related function modules, if any to be used in the above code. If no requirements are needed then keep this blank. add escape charachter before double quotes  within the function definition. Do not make up new functions or modify functions. Only exact function definitions from related function modules should be here>",
  "functioncall": "<entrypoint function name in the above code>(<required argument values. this should not be any variable but an exact value>) if no entrypoint function call is required or entrypoint function is called in above code then keep this blank"
}}

The final code is concatenation of "requirements", "code" and "functioncall". Thus both "requirements" and "code" should contain valid python code.
The final code should not have infinite loops and should run for finite time and halt. 
The "functioncall" should contain the entrypoint function execution string of "code", if required.

The structure of the code will be as follows:
import <any required inbuilt python library>
<New function defintion with arguments and proper indentation. function body may contain python loops, conditional statements, arithmetic operations, python inbuilt functions,
logical operations, variable assignments, complex math operations, 
function calls with appropriate parameters that to related function modules that are defined above.
Always return the data that you want to send to the main AI agent. 
The return data can be any data collected from the environment, user , other AI agent or ant specific return data mention in the action plan.
The above entrypoint function call should not be present here.>

Following is the action code generated for the previous actionplan. 
Previous action code:
   {currentcode}
Here is the code error recieved while executing the full program (concatenation of requirements, code and functioncall) in the environment.
Code error:
   {error}
If code error is available then update the Previous action code (both code and requirements) to remove the code error. Identify if the error occured in requirements, code or functioncall and Make sure to modify them as required, at any cost to remove all errors. Make sure not to create any infinite loops. It should run for finite time.


AI: 
    
"""

ACTORPROMPTINPUTVARIABLES = ["envobjective","actionplan","actions", "currentcode", "prevactionplan",  "error"]


# removecodeerror = """System: You are a Python3 code corrector. Based on the log of the code error you modify the code and make sure the code runs successfully.
 
# Here is the algorithm based on which the code has been generated

# """

 
searchertemplate = """System: You are a part of an AI agent called neo. You need to derive a model of the percieved problem environment from action perception trace.
You can use the list of related similar environments to derive the new one.
Update on top of the current estimated environment based on the updated action perception trace and critique.
The output should always be strictly generated in the following json structure. Add escape charachters wherever required to make the following a valid json definately.
{{  
 "description": <a short summary of the environment>,
 "objective": <objective of the AI agent neo in the problem environment>,
 "beliefaxioms": <axioms of the environment as derived from the action perception trace in free text form. It states the rules or causal relations of how the environment reacts to different actions. It should not state the rules of the actionplan. It should state how the environment responds on different actions and what actions brings most reward and what actions brings least. The axioms should be complete in itself. It should not refer to environment response or any other objects.>
 }}

Following are some related environments. You may use some of the axioms in the related environment if there are some obvious similarities. 
Related environments:
    {relatedenvironments}

Here is the action perception trace. The action is taken by the agent Neo and reponse provided by the environment against corresponding action.
Action Perception trace:
    {ACPtrace}
      
Here is the current estimated environment. If it is available, You should update this environment based on the historical action perception trace.
Current estimated environment:
    {beliefenvironment}
    
       
AI:

"""

#Critque:
#       {critique}


SEARCHERPROMPTINPUTVARIABLES = ["relatedenvironments","ACPtrace","beliefenvironment"] #, "critique"


# DEFAULTCRITIQUEOBJECTIVE = """You are a critique of actions taken by an AI agent.
# The actions should satisfy the environment objective. The perceptions from the environment contains the feedback signal about the action.
# Based on the action perception trace and Environment objective provide a positive or negative reinforcement.
# Use the Environment axioms and the previous critique to provide detail reason of the feedback.
# The output should be in the following json format.
# {"feedback": <positive or negative reinforcement. It can be a real number between -1 and 1>,
# "reason": <reason for the feedback> }
# """

# critiquetemplate = """System: {objective}
    
    # Environment objective:
        # {envobjective}
    # Environment axioms:
        # {beliefenvironmentaxioms}
    
    # Previous Critique:
        # {critique}
    
    # Action Perception trace:
       # {ACPtrace}
       
    # AI:  

# """

critiquetemplate = """System: You are a AI critique of actions taken by an autonomous agent who is situated in the following environment.
Environment:
        {beliefenvironment}

The following is an action plan generated for the above environment. should  
Action plan:
   {actionplan}
You need to generate a critique for the above action plan. You should provide a positive feedback if actionplan meet the environment objective in long term and the actions does not go against the belief axioms (only if belief axioms are not blank). Else you should provide a negative feedback. You provide a neutral feedback if you cannot determine either case.


The following response from the environment may contain the feedback signal about the action.
Environment response:
   {perception}
If the abouve response contains any feedback signal then update your critique accordingly. Give more importance on environment response for updating the feedback value. If the environment response gives negative feedback then always update the feedback with negative value.

The output should be in the following json format. In no case the output should deviate from the following prescribed format.
{{
  "feedback": <positive or negative reinforcement. It can be a real number between -1 and 1>,
  "reason": <a detailed reason for the feedback based on action plan, environment response, beliefaxioms (if available) and objective> 
}}

    
AI:  """

CRITIQUEPROMPTINPUTVARIABLES = ["beliefenvironment", "actionplan", "perception"]


codequivalencetemplate = """System: You are a python code equivalence checker.
If Code 1 and Code 2 are definately semantically equivalent then output True else output False.
    Code 1:
        {code1}
        
    Code 2:
        {code2}
    AI:
"""

CODEEQUIVALENCEVARIABLES = ["code1", "code2"]


planequivalencetemplate = """System:  Determine if the following two plans are algorithmically exactly equal. If they are equal then output True else False. If any one of them is blank then output False

plan 1:
  {historicalactionplan}
  
plan 2:
  {generatedactionplan}
  
Output should be strictly either True or False.

example output:

 example 1:
   True

 example 2:
   False

AI:
"""

PLANEQVVARIABLES = ["historicalactionplan","generatedactionplan"]